### ISSUE TITLE
Improve wtr-is-size

### ISSUE THREAD

**Issue by KittyGiraudel** [kaishin/water.scss#7]
``` scss
@function wtr-is-size($value) {
  $list-length: length($value);

  @if $list-length == 1 {
    @return wtr-is-length($value)
      or wtr-is-percentage($value)
      or wtr-list-contains($wtr-width-values, $value)
      or wtr-is-global-value($value);
  } @else if $list-length == 2 {
    $first-value: nth($value, 1);
    $second-value: nth($value, 2);
    $valid-first-value:
      wtr-is-length($first-value)
      or wtr-is-percentage($first-value);
    $valid-second-value: wtr-list-contains($wtr-box-sizing-width-values, $second-value);
    @return $valid-first-value and $valid-second-value;
  } @else {
    @return false;
  }
}
```

Any reason not to go recursive?

``` scss
@function wtr-is-size($value) {
  @if length($value) == 1 {
    @return wtr-is-length($value)
      or wtr-is-percentage($value)
      or wtr-list-contains($wtr-width-values, $value)
      or wtr-is-global-value($value);
  }

  $okay: true;

  @each $val in $value {
    $okay: $okay and wtr-is-size($val);
  }

  @return $okay;
}
```
